import NavBar from "./common/header";
import { Inter } from "next/font/google";
// import "./globals.css";
import SSRProvider from 'react-bootstrap/SSRProvider';
import 'bootstrap/dist/css/bootstrap.min.css';
import "/public/style.css";
import Footer from "./common/footer.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        
      <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
    
    
  );
}
